language: d

env:
  - CONFIG="x86_64"

d:
  - dmd-2.074.1
  - dmd-2.073.2
  - ldc

os:
  - linux
  - osx

matrix:
  include:
    - {os: linux, d: dmd-2.073.2, env: CONFIG="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
  exclude:
    - d: dmd-2.074.1
      os: osx
  allow_failures:
    - os: osx
      d: dmd-2.073.2
    - d: dmd-2.074.1

script:
  - travis_wait 30 dub build --arch=$CONFIG --compiler=$DC --build=release
  - cd builder
  - dub build --single --arch=$CONFIG --compiler=$DC --build=release init.d
  - ./selery-init hub
  - dub build --arch=$CONFIG --compiler=$DC --build=release
  - ./selery-init node
  - dub build --arch=$CONFIG --compiler=$DC --build=release
  - ./selery-init default
  - dub build --arch=$CONFIG --compiler=$DC --build=release

notifications:
  - email: false
