language: d

d:
  - dmd-2.074.1
  - dmd-2.073.2
  - ldc

os:
  - linux
  - osx

matrix:
  exclude:
    - d: dmd-2.074.1
      os: osx
  allow_failures:
    - os: osx
      d: dmd-2.073.2
    - d: dmd-2.074.1

script:
  - travis_wait 60 dub build --compiler=$DC --build=release
  - cd builder
  - dub build --single --compiler=$DC --build=release init.d
  - ./selery-init hub
  - dub build --compiler=$DC --build=release
  - ./selery-init node
  - dub build --compiler=$DC --build=release
  - ./selery-init default
  - dub build --compiler=$DC --build=release

notifications:
  - email: false
