language: d

d:
 - dmd-2.073.2
 - ldc

script:
 - cd build
 - dub build --single --compiler=$DC --build=release hub.d
 - dub init.d --compiler=$DC
 - dub build --single --compiler=$DC --build=release node.d

notifications:
 - email: false
