language: d

env:
  - CONFIG="x86_64"

d:
  - dmd-2.074.0
  - dmd-2.073.2
  - ldc

os:
  - linux
  - osx

matrix:
  include:
    - {os: linux, d: dmd-2.073.2, env: CONFIG="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd-2.073.2, env: CONFIG="docs"}
  exclude:
    - d: dmd-2.074.0
      os: osx
  allow_failures:
    - os: osx
      d: dmd-2.073.2
    - d: dmd-2.074.0

before_install:
  - chmod +x .ci/build.sh
  - chmod +x .ci/docs.sh

script:
  - cd .ci
  - if ["$CONFIG" = "docs"]; then
  -   ./docs.sh
  - else
  -   ./build.sh
  - fi

notifications:
  - email: false
