language: d

d:
  - dmd-2.075.0
  - dmd-2.073.2
  - ldc-1.3.0

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
      d: dmd-2.073.2
    - d: dmd-2.075.0

script:
  - travis_wait 60 dub build --compiler=$DC --build=release
  - cd builder
  - dub build --single --compiler=$DC --build=release init.d
  - ./selery-init hub
  - dub build --compiler=$DC --build=release
  - ./selery-init node
  - dub build --compiler=$DC --build=release
  - ./selery-init default
  - dub build --compiler=$DC --build=release
  - ./selery-init portable
  - dub build --compiler=$DC --build=release
  - cd ..
  
after_success:
  - ./selery-hub --about
  - ./selery-node --about
  - ./selery-default --about

notifications:
  - email: false
