language: d

env:
  - ARCH="x86_64"

d:
  - dmd-2.073.2
  - ldc
  - gdc

os:
  - linux
  - osx

matrix:
  include:
    - {os: linux, d: dmd-2.073.2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: osx, d: dmd-2.073.2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
  allow_failures:
    - d: gdc

script:
  - cd build
  - dub init.d --arch "$ARCH" --compiler=$DC --build=release
  - travis_wait 30 dub build --single --arch "$ARCH" --compiler=$DC --build=release lite.d
  - dub build --single --arch "$ARCH" --compiler=$DC --build=release hub.d
  - dub build --single --arch "$ARCH" --compiler=$DC --build=release node.d

notifications:
  - email: false
