language: d

d:
 - dmd-2.073.2
 - ldc
 
install:
 - mkdir -p hub/resources
 
script:
 - cd hub && dub build --compiler=$DC --build=release
 - cd ../node && dub init.d --compiler=$DC
 - dub build --compiler=$DC --build=release
