language: d

env:
  - ARCH="x86_64"

d:
  - dmd-2.074.0
  - dmd-2.073.2
  - ldc

os:
  - linux
  - osx

matrix:
  include:
    - {os: linux, d: dmd-2.073.2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
#    - {os: osx, d: dmd-2.073.2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
  exclude:
    - d: dmd-2.074.0
      os: osx
  allow_failures:
    - os: osx
      d: dmd-2.073.2
    - d: dmd-2.074.0

script:
  - cd build
  - dub init.d --arch=$ARCH --compiler=$DC --build=release
  - travis_wait 30 dub build --config=lite --arch=$ARCH --compiler=$DC --build=release
  - dub build --config=hub --arch=$ARCH --compiler=$DC --build=release
  - dub build --config=node --arch=$ARCH --compiler=$DC --build=release

notifications:
  - email: false
