language: d

d:
 - dmd
 - ldc
 
install:
 - cp -r common hub/src
 - cp -r common node/src
 - mkdir -p hub/resources
 
script:
 - cd hub && dub build --compiler=$DC
 - cd ../node && $DC init.d src/common/sel.d src/common/path.d src/common/util/format.d && ./init
 - dub build --compiler=$DC
