language: d

d:
 - dmd
 - ldc
 
install:
 - cp -r common hub/src
 - cp -r common node/src
 - cp -r common node
 
script:
 - cd hub && dub build --compiler=$DC && cd ..
 - cd node && $DC -run init.d && dub build --compiler=$DC && cd..
