language: d

env:
  - ARCH="x86_64"
  - CONFIG="release"

d:
  - dmd-2.074.0
  - dmd-2.073.2
  - ldc

os:
  - linux
  - osx

matrix:
  include:
    - {os: linux, d: dmd-2.073.2, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd-2.073.2, env: CONFIG="docs"}
  exclude:
    - d: dmd-2.074.0
      os: osx
    - config: ddoc
      os: osx
    - config: ddoc
      d: ldc
    - config: ddoc
      d: dmd-2.074.0
  allow_failures:
    - os: osx
      d: dmd-2.073.2
    - d: dmd-2.074.0

script:
  - cd .ci
  - if ["$CONFIG" = "docs"]; then
  -   ./docs.sh
  - else
  -   ./build.sh
  - fi

notifications:
  - email: false
