platform:
  - x86
  - x64

configuration:
  - debug
  - release

environment:
  SEL: "2.0.0"
  matrix:
    - DC: dmd
      DVersion: 2.073.2
    - DC: ldc
      DVersion: 1.2.0

matrix:
  allow_failures:
    - platform: x86

skip_tags: true
branches:
  only:
    - master

artifacts:
  - path: build\hub.exe
    name: sel-hub
  - path: build\node.exe
    name: sel-node
  - path: build\lite.exe
    name: sel-lite
  - path: build\sel-portable-%SEL%.exe
    name: sel-portable

install:
  - ps: function SetUpDCompiler
        {
            if($env:platform -eq "x86"){
              $env:DConf = "m32";
              $env:Dmodel = "32";
            }
            elseif($env:platform -eq "x64"){
              $env:DConf = "m64";
              $env:Dmodel = "64";
            }
            if($env:DC -eq "dmd"){
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
              echo "finished.";
              pushd c:\\;
              7z x dmd.7z > $null;
              popd;
            }
            elseif($env:DC -eq "ldc"){
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-win$($env:Dmodel)-msvc.zip" -OutFile "c:\ldc.zip";
              echo "finished.";
              pushd c:\\;
              7z x ldc.zip > $null;
              mv ldc2-$($version)-win$($env:DModel)-msvc ldc2;
              popd;
            }
        }
  - ps: SetUpDCompiler
  - powershell -Command Invoke-WebRequest http://code.dlang.org/files/dub-1.2.1-windows-x86.zip -OutFile dub.zip
  - 7z x dub.zip -odub > nul
  - set PATH=%CD%\%binpath%;%CD%\dub;%PATH%
  - dub --version

before_build:
  - ps: if($env:platform -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
            $env:Dmodel = "32";
          }
        elseif($env:platform -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
            $env:Dmodel = "64";
        }
  - ps : if($env:DC -eq "dmd"){
           $env:PATH += ";C:\dmd2\windows\bin;";
         }
         elseif($env:DC -eq "ldc"){
           $env:PATH += ";C:\ldc2\bin";
           $env:DC = "ldc2";
         }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'
  - mkdir plugins
  - git clone https://github.com/sel-plugins/commands.git plugins\commands
  - echo %PLATFORM%
  - echo %CONFIGURATION%
  - echo %DC%
  - echo %Darch%

build_script:
 - cd build
 - dub init.d --portable --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
 - dub build --config=lite --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
 - rename lite.exe sel-portable-%SEL%.exe
 - rmdir ..\plugins /s /q
 - dub init.d --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
 - dub build --config=hub --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
 - dub build --config=node --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%
 - dub build --config=lite --arch=%Darch% --compiler=%DC% --build=%CONFIGURATION%

test_script:
 - '%DC% --version'
